### ISSUE TITLE
Allow users to pick notebooks to expose to Mya

### ISSUE THREAD

**Issue by fivesquared** [fivesquared/Mya#10]
> the "Connect Evernote Notebook" is a bit out of place though. if my account has notebooks A,B,C,D,E and a checklist returns notes in A,D at t1 and at t2, the same checklist can return notes in A,B,D and at t3 notes in A,B,D,E and t4 returns notes in A,B,C,D,E I should be able to exclude notebooks D and E entirely. I don't have a solution for you - you are dealing with a complex issue and privacy concerns. most Evernote users feel their data is rather private so it will be challenging to gain access to their notebooks until you can make it _extremely_ fine-grained
> **2.0@chinarut**

**Comment by fivesquared** [comment]
Please NOTE: SHARING a Notebook doesn't expose other notebooks and cross references.

**Comment by chinarut** [comment]
there are two sides of the fence:  some users will want 20% of their notebooks available to Mya and others will want to exclude 20% of their notebooks to Mya.  And to be clear, to exclude a notebook is more along the lines of not giving you permission to open that notebook whatsoever (opposed to restricting a result set)
