### ISSUE TITLE
Notebook List incomplete

### ISSUE THREAD

**Issue by fivesquared** [fivesquared/Mya#11]
Verify bridge cache is managed for listAllNotebooks in EN SDK V2 different from EN SDK V1

**Comment by fivesquared** [comment]
https://uploads.intercomcdn.com/i/o/2271777/2a56852c4b54cbd99a59f59f/Screenshot%25202015-09-28%252015.10.57.png

**Comment by chinarut** [comment]
now that I understand what the select Notebook feature is for - one of the notebooks from my list that is missing happens to be "Mya" ;)    I would love to see an alphabetical list of both personal and business notebooks.
